dataset:
  name: sunrgbd_nyu_object
  root: "E:/dataset/SUNRGBD"          # SUNRGBD root directory
  sensor: "kv1"
  subset: "NYUdata"                   # NYUdata

  rgb:
    dir: "image"
    ext: ".jpg"
    pattern: "{id}.jpg"

  depth:
    dir: "depth"
    ext: ".png"
    pattern: "{id}.png"

  task: "object_roi"                 # Key: image pair
  roi:
    index_train: "E:/dataset/SUNRGBD/roi_index/roi_train.jsonl"
    index_val: "E:/dataset/SUNRGBD/roi_index/roi_val.jsonl"
    index_test: "E:/dataset/SUNRGBD/roi_index/roi_test.jsonl"
    min_box_size: 20
    drop_unknown: true

  preprocessing:
    image_size: [224, 224]
    depth:
      fill_missing: 0
      # clip_max_meters: 5.0          # Cut off the depth at a distance
      normalize: "minmax"             # Use either minmax or zscore as the baseline.
      to_3ch: false

  split:
    method: "by_image"                  # First, randomly assign tasks and run the pipeline.
    train: 0.7
    val: 0.15
    test: 0.15
    seed: 42
    stratify: false                  # Hierarchical categorization

  model:
    name: "resnet18"


experiment:
  seed: 42
